services:
  sncfconnect:
    build:
      context: ../..
      dockerfile: ../docker/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - sncfconnect
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:17.5-alpine3.21
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeit
      POSTGRES_DB: sncfconnect_db
    networks:
      - sncfconnect
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U sncfconnect_user" ]
      interval: 1s

networks:
  sncfconnect:
    external: false

volumes:
  db:
    driver: local